### PR TITLE
[expo][example] Updated example functionality

### PR DESCRIPTION
**Pull request by EvanBacon**
# Why 

Added examples of some common functionality with Expo. Seems valuable for people who want to copy/paste the functionality. 

# How

* Updated CustomView
* Added Touchable to map element
* Added map linking
* Added CustomActions 
* Added AccessoryBar
* Added Footer

# Test 

You can run it locally or in a snack. Here is a photo of the results:

simulator screen shot - iphone xr - 2019-03-01 at 15 19 49

### CODE REVIEW

**Comment by EvanBacon** [comment]
Planning to fix the navigation in another PR. This one is getting kinda heavy. @xcarpentier is it cool if I use react-navigation?

**Comment by EvanBacon** [comment]
[HOLD] I'm going to merge the media utils

**Comment by EvanBacon** [comment]
Ready to go now 😄

**Comment by xcarpentier** [comment]
> Planning to fix the navigation in another PR. This one is getting kinda heavy. @xcarpentier is it cool if I use react-navigation?

yes ok

**Pull request merged**
