### PR TITLE
Added accessibilityLabel prop on send button

### PR DESCRIPTION
**Pull request by omeraplak**
For easy testing.

### CODE REVIEW

**Comment by omeraplak** [comment]
@xcarpentier i resolved conflict.
https://github.com/FaridSafi/react-native-gifted-chat/pull/642/commits/ede56c65f834d3e1dbd60283b81d83de959ecb5e

thanks

**Comment by cooperka** [comment]
The [docs](https://facebook.github.io/react-native/docs/accessibility.html) for features like this are extremely poor -- will this change prevent screen readers from seeing the text inside the TextInput? Have you tested on a real device? If it still works then this LGTM.

**Comment by xcarpentier** [comment]
@omeraplak What kind of tools are you using for e2e test: detox or appium or other?

**Comment by omeraplak** [comment]
@xcarpentier i using to appium. It's working perfect.

**Pull request closed without merging**
