### PR TITLE
Move react-native-video to peer dependancy

### PR DESCRIPTION
**Pull request by ahartzog**

### CODE REVIEW

**Comment by ahartzog** [comment]
Same issue as before - I keep seeing people hitting this issue with duplicate views when also using react-native-video.

I don't know Jest well enough to stub in the react-native-video mock, but if you guys can point me in the right direction I'm happy to try or see how it's done.

**Comment by xcarpentier** [comment]
Need to fix jest snapshot testing. Maybe by mocking Video component?

**Comment by ahartzog** [comment]
Yes @xcarpentier agreed, I just don't know how to do that! Any other contributors more familiar with testing who could mock it in?

**Comment by iLevye** [comment]
Is there a quick way to work around duplicate video component issue when you guys issuing about that?

**Comment by ahartzog** [comment]
Ok I finally found some time to do this @xcarpentier. 

The test isn't particularly useful, but it passes!

**Comment by loga4** [comment]
+1

**Comment by xcarpentier** [comment]
Thanks
I've copied your modification here e0efb3a48658610c16cce21e716ad288a519fc3b

**Pull request closed without merging**
