### PR TITLE
Improve perf

### PR DESCRIPTION
**Pull request by xcarpentier**
https://github.com/FaridSafi/react-native-gifted-chat/issues/1048

### CODE REVIEW

**Comment by xcarpentier** [comment]
@sibelius because that cause issue on large list of message (+200). Too much memory usage due to the deep shallow equal (blank screen, crash).

**Comment by xcarpentier** [comment]
@sibelius do you have any other suggestions ?
BTW we passed thought all component huge amount of props and shallowequal did the work and consume too much memories that our thread not display any UI. (ie. https://github.com/FaridSafi/react-native-gifted-chat/pull/1076)

**Comment by sibelius** [comment]
Good enough for me

**Comment by brunocascio** [comment]
Is expo snack working? Code looks good for me

**Comment by ChrisEdson** [comment]
This PR is super buggy, for a bunch of reasons.

It means that if you change any property in a message (like pending etc), the FlatList will not re-render because of the `shouldComponentUpdate` in MessageContainer.js. As the actual length of the messages array isn't changing, then nothing will update.

There's also bigger isssues in the PR - in that `shouldComponentUpdate` function, `next.extraData` and `current.extraData` is referenced. `next` is `this.props.messages` - so you're referencing the `extraData` property on a messages array. The same for `loadEarlier`.

I highly recommend using flow for things like this, it would have picked this up immediately - rather than merging something in that will break everyone's code.

**Comment by xcarpentier** [comment]
@ChrisEdson please review: https://github.com/FaridSafi/react-native-gifted-chat/pull/1101

**Comment by ChrisEdson** [comment]
Ah sorry my comment sounded really mean! 

I just mean adding Flow (or TypeScript). Then it would flag that you were trying to access `extraData` on an Array type (`messages`). TypeScript would do the same, but is a bit more work to add. Flow is pretty quick!

**Comment by xcarpentier** [comment]
@ChrisEdson TypeScript is just better. I really don't want to introduce Flow.

So migrate to TypeScript?!? 
Challenge accepted!

Just need to know if eough contributor will continue or not?

**So please vote here with a 👍 if you see it ;)**

**Comment by xcarpentier** [comment]
#1190

**Pull request merged**
