### PR TITLE
[fix] issue of Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider with expo SDK 46

### PR DESCRIPTION
**Pull request by kyoto21**

### CODE REVIEW

**Comment by KieQuang** [comment]
+1

**Comment by kukuandroid** [comment]
+1

**Comment by renruyi** [comment]
+1

**Comment by qaws5503** [comment]
Sorry to bother you, but how can I install this PR? I'm using yarn and I've tried the following:
```
yarn add FaridSafi/react-native-gifted-chat#2278/head
yarn add FaridSafi/react-native-gifted-chat#pull/2278/head
yarn add FaridSafi/react-native-gifted-chat#refs/pull/2278/head
```
And none of it works.
Thanks for your help🙏

**Comment by Johan-dutoit** [comment]
Should be fixed with https://github.com/FaridSafi/react-native-gifted-chat/pull/2353 and https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v2.0.0

**Pull request closed without merging**
