### PR TITLE
pending tick

### PR DESCRIPTION
**Pull request by LucasMonteiro1**

### CODE REVIEW

**Comment by sibelius** [comment]
testing are failing

can you provide a test plan?

**Comment by LucasMonteiro1** [comment]
lint is failing by the [jsx-a11y/accessible-emoji](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/accessible-emoji.md) rule, but is working in the test.

screen

**Comment by sibelius** [comment]
Can you fix the lint?

**Comment by LucasMonteiro1** [comment]
How to fix? I tried disabling the lint on the line and finding a replacement, but it did not work.

**Comment by sibelius** [comment]
can you disable lint in this case?

**Pull request merged**
