### PR TITLE
Changed direct use of the bottomOffset prop into getter / setter, all…

### PR DESCRIPTION
**Pull request by ckuijjer**
Changed direct use of the bottomOffset prop into getter / setter, allowing the bottomOffset only to be used when the keyboard is shown. Fixed initial render issue.

### CODE REVIEW

**Comment by ckuijjer** [comment]
See #169

**Comment by FaridSafi** [comment]
Thank you, I'll test tomorrow

**Comment by FaridSafi** [comment]
I merged your PR manually https://github.com/FaridSafi/react-native-gifted-chat/commit/2133625d9befd4f85be958272470fc522fa9c236

**Comment by FaridSafi** [comment]
I tested on Android and it's not enough to handle bottom views properly.
You will also need to hide the views below the chat when the keyboard appears.

Feel free to submit a PR for Android

**Comment by ckuijjer** [comment]
I might take a look at the Android issue, seems like a good reason to finally play with the Android development tools.

**Pull request closed without merging**
