### PR TITLE
Adds AlignTop Property

### PR DESCRIPTION
**Pull request by mattvv**
Sometimes client's are fun!
My client demanded that the chat appeared at the top just like iMessage. This commit adds the option to do this.

### CODE REVIEW

**Comment by mattvv** [comment]
Updated this to satisfy the linter. Let me know if I need to do anything else. Would like to get this onto the main branchline so I can stop using my fork

**Comment by xcarpentier** [comment]
Hi, 
Can you share a screenshot of it?
Thanks

**Comment by mattvv** [comment]
Sure,
This is from my test app so ignore the crappy color scheme:
image

**Comment by xcarpentier** [comment]
Is that possible to add it screenshot on readme? In this PR. It's a nice. Maybe an new _screenshots_ section...

**Comment by mattvv** [comment]
I'm sorry mate, I don't have the time to set up a staged photo that looks nice for it :(

**Comment by xcarpentier** [comment]
screenshot 2019-02-08 at 18 18 00

**Comment by azzadrood** [comment]
Is this published to npm? I see the props appear in readme but i try to use it and it is not working.

Using  `"react-native-gifted-chat": "^0.7.2"`

**Comment by xcarpentier** [comment]
Not yet

**Comment by Shpadoinkle** [comment]
How you going guys, any ETA on the release of alignTop props to npm?

**Pull request merged**
