### PR TITLE
Fix/avatar

### PR DESCRIPTION
**Pull request by maxs15**
I was trying to override the Avatar in order to support local images, but it wasn't possible to do it properly (props.renderAvatar is only called in one part of the template)
I did several modifications in order to fix these issues:
- I refactored the Avatar component for being able to override the component
- I modified the GiftedAvatar component in order to be able to load a local image

Tested on emulator + device.
Let me know @FaridSafi if it looks good on your side to merge.

Thanks !

### CODE REVIEW

**Comment by florianbepunkt** [comment]
Hey @maxs15, can you give an example of overriding the avatar with your PR?

**Comment by maxs15** [comment]
@florianbepunkt, just use the renderAvatar property specified in the docs, didn't add any new property, just fixed an issue to override the avatar properly

**Comment by xavieramoros** [comment]
@kfiroo @maxs15 why this PR isn't merged, is there something wrong? 

I'm stumbling into the same issue, designers decided to remove the avatar ;)

**Comment by maxs15** [comment]
Well @xavieramoros, I'm not the one deciding to merge PRs..

**Comment by xavieramoros** [comment]
I know @maxs15. Thanks for the fix, works perfectly!

**Comment by kfiroo** [comment]
@maxs15 @xavieramoros Hey, sorry guys, I was AFK for a month :)
I see we have some conflicts, if you could resolve them I would try to merge this PR

**Comment by mackenziemance** [comment]
Is there still no support for this feature ??

**Comment by hegelstad** [comment]
Bump

**Pull request closed without merging**
