### PR TITLE
Fix position of `parsePatterns` example

### PR DESCRIPTION
**Pull request by piranna**
Example was wrongly set after `maxComposerHeight` option.

### CODE REVIEW

**Comment by piranna** [comment]
I have added support to transpile this project from JSX to Javascript as it's recomended by `create-react-native-app` team.

**Comment by piranna** [comment]
Can someone be able to merge this?

**Comment by piranna** [comment]
Why has been this clossed?

**Comment by xcarpentier** [comment]
Sorry, because it's apparently already fixed.

**Comment by piranna** [comment]
The position of `parsePatterns` in `README.md` is fixed, but the `prepare` script to be able to use the project from a git repo isn't...

**Pull request closed without merging**
