### PR TITLE
Fix expo import

### PR DESCRIPTION
**Pull request by mattvv**
Pulling from latest I had an issue with my project importing expo, even though isExpo() is false. It turns out that the require is pulled out in the static analysis and executed first. So I just added some fluff to get past that.

### CODE REVIEW

**Comment by xcarpentier** [comment]
I think the expo thing is not a good path by the way. I will remove it as soon as possible because we still have the possibility to use renderVideo, and I guess it should work also.

**Comment by mcmar** [comment]
@mattvv @xcarpentier What is the last good version of this library? I'm currently unable to compile with this lib unless I'm using expo. Just need to figure out the last working version so I can downgrade to that

**Comment by mattvv** [comment]
I have to be honest. I had the same issue @mcmar which is why I fixed this, as I was implementing an unrelated feature #1124

**Comment by xcarpentier** [comment]
Expo thing is not released at all (left = `0.7.2`; right = master): https://github.com/FaridSafi/react-native-gifted-chat/compare/9db9d64...master

@mcmar you have to use `0.7.2`. Do you have any trouble with `0.7.2` version?

As I said I will remove Expo import because it's not required, we can use `renderMessageVideo` instead.

Can you both please copy past here your error on your build?

**Comment by mattvv** [comment]
@xcarpentier it just fails trying to import expo, even though isExpo() is false, the require import is still pulled out of the block and attempted to be imported

**Comment by xcarpentier** [comment]
@mattvv ok, I will remove it now :)

**Pull request closed without merging**
