### PR TITLE
add day format as calendar

### PR DESCRIPTION
**Pull request by kesha-antonov**
I saved format of current version of Day and added ability to pass dayFormat to use in calendar() of moment.

Hence we can have 'TODAY', 'YESTERDAY' etc. Instead of '16 Aug. 2016' when it was yesterday

### CODE REVIEW

**Comment by FaridSafi** [comment]
Hi!
I tried this before, the issue is that `moment` supports 'TODAY', 'YESTERDAY' only in english.

**Comment by kesha-antonov** [comment]
I disagree with you. Now it supports in many languages. Well, russian and english at least
https://github.com/moment/moment/blob/develop/src/locale/ru.js#L73

**Comment by kesha-antonov** [comment]
I bet and other languages too.
Clicked random and saw it: https://github.com/moment/moment/blob/develop/src/locale/pl.js#L55

**Comment by FaridSafi** [comment]
for example in french it's "Aujourd'hui à 15:00"
I would like to display only the day since the time is already displayed inside the bubble

**Comment by kesha-antonov** [comment]
Ok. Got it.

So now you can copy from https://github.com/moment/moment/blob/develop/src/locale/fr.js#L23
```
        sameDay: '[Aujourd\'hui à] LT',
        nextDay: '[Demain à] LT',
        nextWeek: 'dddd [à] LT',
        lastDay: '[Hier à] LT',
        lastWeek: 'dddd [dernier à] LT',
        sameElse: 'L'
```

and pass it to Chat like this:
```
dayFormat: {
        sameDay: '[Aujourd\'hui]',
        nextDay: '[Demain]',
        nextWeek: 'dddd',
        lastDay: '[Hier]',
        lastWeek: 'dddd [dernier]',
        sameElse: 'L'
}
```

I don't know French so correct me if I have typos here :)

**Pull request closed without merging**
