### PR TITLE
add prop hideInputToolbar

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by kfiroo** [comment]
@kesha-antonov Hey,
Wouldn't using `renderInputToolbar` to return `null` or an empty `View` have the same result?

**Comment by kesha-antonov** [comment]
@kfiroo Hey! Thanks, I'll try it!

**Comment by kesha-antonov** [comment]
@kfiroo No. When I return ```null/<View/>``` in ```renderInputToolbar``` it is blank but height is not 0.
screen shot 2017-01-20 at 13 33 54

**Comment by kfiroo** [comment]
We need to think this through. The proper way to resolve this, in my opinion, is to have the `InputToolbar` dynamically resize according to its content.
Not sure why this isn't the case right now, maybe there are some technical difficulties?

**Pull request closed without merging**
