### PR TITLE
Allow pass 'multiline:false' to 'Composer' component

### PR DESCRIPTION
**Pull request by fengliu222**
I try to pass render custom composer param.
When i pass `multiline:false` to the composer , i got a red box.

'e.nativeEvent.contentSize' is not exist when `multiline` param set to false.
So i fix this problem. ( oh my pool english ........)

### CODE REVIEW

**Comment by fengliu222** [comment]
usage:

```jsx
  _renderComposer(props) {
    return (
      <Composer
                {...props}
                textInputProps={{
                  returnKeyType: 'send',
                  multiline: false,
                  onSubmitEditing : (event) => {
                    props.onSend({ text : event.nativeEvent.text.trim() }, true);
                  }
                }}
      />
    )
  }
```

**Comment by FaridSafi** [comment]
Thank you, I'll test tomorrow

**Comment by kfiroo** [comment]
This PR now has 2 separate fixes, for `multiline` and for `renderAvatar`.
Maybe we should split it into two PRs?

**Comment by FaridSafi** [comment]
Looks good, thank you!

**Pull request merged**
