### PR TITLE
Optimize rendering and keyboard smoothness

### PR DESCRIPTION
**Pull request by kesha-antonov**
Hi

- I did a lot of memoization to prevent extra re-renders.
- added `useAnimatedKeyboard` to make appearing smooth on ios and android (!) https://docs.swmansion.com/react-native-reanimated/docs/device/useAnimatedKeyboard/

This PR should improve performance A LOT
There're also plenty of room for improvements left

Fixes  https://github.com/FaridSafi/react-native-gifted-chat/issues/2191

Please give it a try here: `"react-native-gifted-chat": "kesha-antonov/react-native-gifted-chat#43625da0ae36d983c339c0d79ae900c8778f5241"`

Note that you need to change import to `from 'react-native-gifted-chat/src'`

https://github.com/FaridSafi/react-native-gifted-chat/assets/11584712/fa552bf1-7935-45d4-8162-f6014b2e3ce1

https://github.com/FaridSafi/react-native-gifted-chat/assets/11584712/590b5022-f6af-4b6b-9703-c093d521b675

### CODE REVIEW

**Comment by AounNaqvi173** [comment]
hi there , I wanted to use your patch so  i installed  it  and but after installation this is the react-native-gifted-chat folder in node modules ,
image

**Comment by AounNaqvi173** [comment]
ok

**Comment by AounNaqvi173** [comment]
it works thanks ,   but i am facing an issue with my previous implementation for scroll to a message from reply message for which i used  scrollToIndex  , with this patch it is not that performant do you how can i do that , i mainly wanted to use the keyboard smoothness feature

**Comment by kesha-antonov** [comment]
> it works thanks , but i am facing an issue with my previous implementation for scroll to a message from reply message for which i used scrollToIndex , with this patch it is not that performant do you how can i do that , i mainly wanted to use the keyboard smoothness feature

Sorry, idk
You can tweak my fork to make it work

**Comment by AounNaqvi173** [comment]
Okay thanks

**Pull request merged**
