### PR TITLE
Fixed the empty background cannot scroll problem

### PR DESCRIPTION
**Pull request by penghouho**

### CODE REVIEW

**Comment by cutenesss** [comment]
@penghouho have this been merged?

**Comment by penghouho** [comment]
@cutenesss I think it is not merged, the main change is wrapped the View in TouchableWithoutFeedback so that the view cannot be scrolled in file src/Message.tsx, thanks.

**Comment by cutenesss** [comment]
image
thank you for the fixing. so this is the part that we need to fix this?

**Comment by penghouho** [comment]
@cutenesss As far as I know, yes, but maybe you need to test it on your side first to ensure it, because it is change introduced one year ago. thanks.

**Pull request closed without merging**
