### PR TITLE
Change deprecated View.propTypes to ViewPropTypes

### PR DESCRIPTION
**Pull request by mgustin12**
[477](https://github.com/FaridSafi/react-native-gifted-chat/issues/477)

### CODE REVIEW

**Comment by bitsal** [comment]
@cooperka Why don't you merge it? I see you approved it.

**Comment by cooperka** [comment]
@bitsal I'm not a maintainer, so I don't have permission to merge :(

**Comment by bitsal** [comment]
@cooperka it is sad :(, I've thought if you can approve you can merge... will wait for it

**Comment by cooperka** [comment]
@bitsal I've recently been added as a maintainer, so I'll try to merge this soon. Unfortunately it's a breaking change so I'll try to fix other more general bugs first, and then release a major version with this.

**Pull request merged**
