### PR TITLE
Support touch on background to scroll

### PR DESCRIPTION
**Pull request by hawkup**
Current version cannot touch on background to scroll. I use **TouchableWithoutFeedback** to make GiftChat can scroll when user start touch on background.

gif-chat

### CODE REVIEW

**Comment by xcarpentier** [comment]
To fix the build I’ve made a PR on your fork...

**Comment by hawkup** [comment]
@xcarpentier Thank you, But still failed on this line
```
if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi
```

**Comment by xcarpentier** [comment]
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by xcarpentier** [comment]
Will fix it today, sorry about that.

**Comment by hawkup** [comment]
It's error because didn't set **EXP_USERNAME**, **EXP_PASSWORD**, **GITHUB_USERNAME** and **GITHUB_TOKEN** follow this link https://github.com/FormidableLabs/appr#enable-travis

**Comment by xcarpentier** [comment]
Those variables are setted! But travis remove it when come from external PR, for security reason.
I will remove this build from externa PR.

**Comment by hawkup** [comment]
Sorry, I didn't check your link clearly. Thank you so much.

**Comment by michaelgmcd** [comment]
@xcarpentier My team is currently seeing this issue (only able to scroll by pressing a bubble). Is there a workaround/fix?

**Comment by wezzy** [comment]
Hi, is there any fix about this issue ? Thanks

**Comment by penghouho** [comment]
May I know if this fix is merged into master branch? the issue is still there.

**Comment by GTuooa** [comment]
???

**Comment by GTuooa** [comment]
> Current version cannot touch on background to scroll. I use **TouchableWithoutFeedback** to make GiftChat can scroll when user start touch on background.
> 
> gif-chat
How it is  done？

**Pull request closed without merging**
