### PR TITLE
Bump version to 0.1.4

### PR DESCRIPTION
**Pull request by gperdomor**
bump version related to renderAvatarOnTop parameter

### CODE REVIEW

**Comment by kfiroo** [comment]
@gperdomor Hey, this is not necessary, I do it when I release a version :)

**Comment by gperdomor** [comment]
@kfiroo i use yarn has dependency manager, how can i get the new version with the renderAvatarOnTop parameter? Both, yarn and npm, downloads the old version

**Comment by dgdavid** [comment]
@gperdomor you can use a [Git](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) or [Github](https://docs.npmjs.com/files/package.json#github-urls) URLs.

For example, I'm using

```json
"react-native-gifted-chat": "git+https://github.com/FaridSafi/react-native-gifted-chat",
````

But, take in mind that it seems `yarn` has an issue with this approach:

https://github.com/yarnpkg/yarn/issues/1573
https://github.com/yarnpkg/yarn/issues/2501

**Comment by kfiroo** [comment]
A better approach is to reference the exact commit you want to use, yarn works well with that
```
    "react-native-view-transformer": "git+https://github.com/kfiroo/react-native-view-transformer#f96b1c52bb1e426d0fb24833f01e7c12204f84d9"
```

**Pull request closed without merging**
