### PR TITLE
RefactorBubbleTicks

### PR DESCRIPTION
**Pull request by danielmejiadev**
- Create a folder with bubble component to separte concepts between styles, component and test.
- Refactor the way of display tick in order to make it more readable for developer.

### CODE REVIEW

**Comment by danielmejiadev** [comment]
@sibelius @xcarpentier  Could you please review this changes?.
I just wrap the component into a folder and separate the styles, test and component in different files. This is jus to make the files shorter and easy to read.

I also refactored the renderTick in order to create variables with readable names, in this way you know where and why the ticks should be displayed.

**Comment by xcarpentier** [comment]
Sorry I'm not OK. 
@sibelius please do not merge this.

**Comment by danielmejiadev** [comment]
Could you please share with me, What is wrong or what should be changed?

**Comment by sibelius** [comment]
I prefer to keep the styles in the same file that uses it

**Comment by danielmejiadev** [comment]
@sibelius Thanks, I got the idea about how can I contribute. So I rewrite the PR with your comments. Please take a look. Again

**Comment by xcarpentier** [comment]
Hi @danielmejiadev,
Thanks for your work.
Can you please keep indentation also because it's hard to see differences when your changes is just another indentation?
Thanks in advance.

**Comment by xcarpentier** [comment]
@danielmejiadev Should we keep this PR regarding other work you started?
I don't think so, then please remove it ;)

**Comment by danielmejiadev** [comment]
@xcarpentier There is not problem. Im gonna remove it

**Pull request closed without merging**
