### PR TITLE
add send video support 

### PR DESCRIPTION
**Pull request by maherzaidoune**

### CODE REVIEW

**Comment by sibelius** [comment]
I’m not sure if this is the right direction t go

I think we should just provide a renderMessage and let user decide what to render

It is impossible to cover all types of messages

**Comment by ahartzog** [comment]
Just like image is supported though, video is a very common use case.

**Comment by Moneemsaadaoui** [comment]
Works like a charm and honestly video support makes life a tad bit easier 🐜🐜

**Comment by sibelius** [comment]
CI is failing, can you fix it?

**Comment by maherzaidoune** [comment]
@sibelius this is a eslint no-use-before-define failure because of the styles variable , while it's a common pattern to put the styles at the bottom of the component file , any suggestion ?

**Comment by sibelius** [comment]
can we disable this lint rule in this specific case?

**Comment by maherzaidoune** [comment]
done

**Pull request merged**
