### PR TITLE
Add onTopReached callback for auto loading earlier messages

### PR DESCRIPTION
**Pull request by ramilushev**

### CODE REVIEW

**Comment by cooperka** [comment]
I rebased and cleaned up, and for me this triggers as soon as the list renders (or the orientation changes), but **not** when it actually gets to the top of the messages.

Maybe it's related to InvertibleScrollView as discussed [here](https://github.com/FaridSafi/react-native-gifted-chat/pull/275#discussion_r86394597). If anyone has suggestions on how to get this to work, please let us know :)

**Comment by Jose4gg** [comment]
Any progress with this implementation, it is the most need for chats with pagination....

**Comment by dorthwein** [comment]
This would be a huge help.  Any progress made?

**Comment by cooperka** [comment]
Hi @Jose4gg and @dorthwein, unfortunately there aren't any updates here, just waiting for a working implementation. If you both could help out and submit a working fix, I would be happy to merge it for you!

**Comment by cooperka** [comment]
Hi @kevinscience, it would be great if you could help out! This will never be fixed until someone in the community decides to fix it.

**Comment by RWOverdijk** [comment]
There's a `loadEarlier` prop, can't that implementation be used? Or does that just always render the item at the top?

**Pull request closed without merging**
