### PR TITLE
Use onContentSizeChange dispite onChange

### PR DESCRIPTION
**Pull request by K-Leon**
Fixes RN 0.46.1 incompatibility

### CODE REVIEW

**Comment by cooperka** [comment]
Thanks for the PR! There's a similar PR here as well: https://github.com/FaridSafi/react-native-gifted-chat/pull/500. Curious what your thoughts are on which fix is better.

Can you please explain why this change is needed and what it does?

**Comment by K-Leon** [comment]
RN dropped support of size props in: https://github.com/facebook/react-native/commit/bac84ce207a0466cec95626131063751eb48b964

**Comment by cooperka** [comment]
Closing in favor of #500. Thanks again for submitting @K-Leon

**Comment by RobertWSaunders** [comment]
Any chance a new version will be released to npm? I have forked the repo to get these changes. Did @FaridSafi stop maintaining this?

**Comment by cooperka** [comment]
@RobertWSaunders I published 2 new versions yesterday, are you able to see them on npm? Something may have gone wrong, please let me know if they're not available.

I'll test this change within the next few days and release it as well. Want to make sure it's not breaking for older versions.

**Comment by RobertWSaunders** [comment]
@cooperka That's awesome, my apologies, I now see the updated version, prior to yesterday it hadn't been updated for a while, thank you for doing that, very useful. 👍

**Comment by cooperka** [comment]
Good to hear! I was just added as a maintainer a few days ago :)

**Pull request closed without merging**
