### PR TITLE
Provide textInput ref (if it exists) to onInputTextChanged calls

### PR DESCRIPTION
**Pull request by chris-divvito**
Hello,

This is just a PR to provide the textInput ref to the onInputTextChanged callback. The specific reason I have made the PR is to deal with an issue specific to Samsung devices using the predictive text keyboard, in which the keyboard retains state when after the input is cleared. As a result, when the user sends a message, the next time they start typing in the input the predictive text keyboard retains the last word of their previous message at the start of the new message. See https://stackoverflow.com/questions/37798584/react-native-when-submitting-a-text-input-in-android-the-word-suggestions-are and https://stackoverflow.com/questions/43233223/react-native-text-input-clear-doesnt-clear-text for a description of the issue. 

I didn't feel like the workaround for this device-specific issue belonged in your library, but I didn't have access to the ref outside of your code to implement it outside the library, thus this PR which provides the ref to the onInputTextChanged callback, and allowing me to do this:

```
onInputTextChanged = (text: string, inputRef?: TextInput) => {
    if (inputRef && text === '') {
      // Dirty workaround for issue with predictive text keyboard on samsung devices
      // See: https://stackoverflow.com/questions/37798584/react-native-when-submitting-a-text-input-in-android-the-word-suggestions-are
      inputRef.setNativeProps({keyboardType:"email-address"});
      inputRef.setNativeProps({keyboardType:"default"});
    }
    // ... normal onChange code
  };
```

If this is not your preferred way to handle this let me know and I can rework the PR :) Thanks for the great work on Gifted Chat

### CODE REVIEW

**Comment by xcarpentier** [comment]
Hello,
Thanks 👌
But why not find a way to fix it into this lib?

**Comment by chris-divvito** [comment]
Sure, I mean it would just be a case of, when the text input is reset, doing:
```
this.textInput.setNativeProps({keyboardType:"email-address"});
this.textInput.setNativeProps({keyboardType:"default"});
```

**Comment by mallelapavank** [comment]
Any update on this PR? This issue turns out to be very annoying on some devices. 
I forked the repo and applied this workaround for my personal use, and it just works without any problems. 
I'd be happy to open a fresh PR with my changes, if that's ok.

**Comment by tomasamado97** [comment]
Can someone check this PR and merge it if its all good? I need it for the same reason @jenni-divvito did.

**Comment by xcarpentier** [comment]
You can create a new PR

**Pull request closed without merging**
