### PR TITLE
Move hash to single message from all messages

### PR DESCRIPTION
**Pull request by kfiroo**
Moving hash to each message should allow MessageContainer to rerender when messages are not changed.
Use ListView with InvertibleListView to easily support a lot of messages and have renderFooter, renderHeader etc.

### CODE REVIEW

**Comment by FaridSafi** [comment]
Thanks for you work @kfiroo 
It seems that messagesHash has better performance than an hash for each messages

Using the following data https://gist.github.com/FaridSafi/803bf49b6fa1f82709dc9c9a5462b861
I appended a new message and it took 3-4 seconds versus 1 second using messagesHash

Note :
ListView should have also
```
          initialListSize={this.props.messages.length}
          pageSize={15} // maybe more ?
```

**Comment by kfiroo** [comment]
Actually `initialListSize` should not be too big, it only indicates how many rows the `ListView` should render in the first render cycle, if that number is too big it will cause the UI thread to hang and the app will feel stuck.
We should render a number that will fit in the screen so the user won't feel the batched loading, `ListView` will take care of loading the others in cycles.

I really think `ListView` is the better solution, rendering a lot of data inline is really discouraged by RN team.
`ListView` also supports native view recycling and not removing views that are not in the viewport to enhance performance.

I will try to improve the `append` performance and I'll ping you again :)

**Comment by kfiroo** [comment]
@FaridSafi Hey :)
So, performance seems to be very good now,
(**note all measurements are in DEV mode so it should be significantly better in production**)
* List only renders `initialListSize` messages so first render takes ~200ms
* Lists with under 100 items `append` takes ~50ms
* Lists with 200 items `append` takes ~100ms
* Lists with 400 items `append` takes ~250ms

Let me know what you think

**Comment by kfiroo** [comment]
There is a bug with previous/next message reference - fixing it now

**Comment by FaridSafi** [comment]
I am testing today :)

**Comment by FaridSafi** [comment]
Thank you @kfiroo
I confirm that appending a message is faster!

I will try to replace `react-addons-shallow-compare` by `shallowequal` to avoid a warning during the installation

**Comment by FaridSafi** [comment]
I released 0.0.4 with your updates. Good work!
Thanks

**Comment by kfiroo** [comment]
@FaridSafi Great! Thanks

**Pull request merged**
