### PR TITLE
Add prop to customise to Text style of timestamps

### PR DESCRIPTION
**Pull request by gianpaj**
Example:

```jsx
<GiftedChat
  messages={this.state.messages}
  onSend={this.onSend}
  renderCustomView={CustomView}
  keyboardShouldPersistTaps="never"
  user={{ _id: 1 }}
  renderBubble={props => {
    return (
      <Bubble
        {...props}
        timeTextStyle={{
          right: { color: 'red' }
        }}
      />
    );
  }}
  parsePatterns={this.parsePatterns}
/>
```

Related to #672

### CODE REVIEW

**Comment by dengue8830** [comment]
why this is not merged?

**Comment by gianpaj** [comment]
I've fixed the linting and test snapshot issues. CI checks have passed :)

**Comment by xcarpentier** [comment]
thanks 👍

**Comment by supunmadhuranga** [comment]
how to change timestamp position?

**Comment by gianpaj** [comment]
@supunmadhuranga 
`right` with `left` are just keys to the prop object:

```jsx
<GiftedChat
  messages={this.state.messages}
  onSend={this.onSend}
  renderCustomView={CustomView}
  keyboardShouldPersistTaps="never"
  user={{ _id: 1 }}
  renderBubble={props => {
    return (
      <Bubble
        {...props}
        timeTextStyle={{
          right: { color: 'red' },
          left: { color: 'blue' }
        }}
      />
    );
  }}
  parsePatterns={this.parsePatterns}
/>
```

**Comment by skizzo** [comment]
So about @supunmadhuranga 's question, how can you change the position of the time so that a bubble on the left side shows the time its right edge, and not the left edge? There's absolutely nothing in the docs about this, so thanks for any hints!

**Pull request merged**
