### PR TITLE
improve send message performance

### PR DESCRIPTION
**Pull request by kfiroo**
Use TextInput.clear() to instantly clear the text input and make sure delayed calls to onChangedText are fixed

### CODE REVIEW

**Comment by kfiroo** [comment]
@FaridSafi let me know what you think.

Please note that this is probably not production ready, only a concept (which I'm currently using in my project) to improve send messages performance.

**Comment by FaridSafi** [comment]
Hello @kfiroo thank you for your work
I didn't test yet, did you try using a real device ?

**Comment by kfiroo** [comment]
@FaridSafi sure, it's on my fork, going to production soon :)
Again, it might not be bullet proof, as I only tested it on my specific use case, but I'll be more then happy to hear what you think and if you have any comment on how to improve it and integrate it into `gifted-chat`

**Comment by bsiddiqui** [comment]
hey @kfiroo any progress on this? happy to help if it'll move things along.

**Comment by kfiroo** [comment]
@bsiddiqui Thanks! As this PR is from a diff of my fork, things got a little messy..
I will clean this up soon and let you know, sorry for the mess.

You can try to use it as it is now by using my fork in your `package.json` if you want - it is supposed to be up to date with this repo.

`"react-native-gifted-chat": "https://github.com/kfiroo/react-native-gifted-chat#0afcf0a9773adc3c45097d93c784f177dc91b9e4"`

**Comment by FaridSafi** [comment]
Hello @kfiroo. Would you like to be able to maintain this repo ?

**Comment by kfiroo** [comment]
@FaridSafi Yeah, sure, I can do that. What's up? You're too busy?

**Comment by FaridSafi** [comment]
Yes, I have to work on other projects. I saw you did a good job with your fixes.
Do you have a NPM account?

**Comment by kfiroo** [comment]
Sure, https://www.npmjs.com/~kfiroo

**Comment by FaridSafi** [comment]
I added you as collaborator in NPM

**Pull request closed without merging**
