### PR TITLE
WIP Quick Replies 

### LINKED ISSUE #826: RFC: Quick Replies
Not sure if this library can do suggested responses but it would be very helpful for people who build chat bots.

Something like this:
customer-chat

Facebook calls them `quick_replies`: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

Kik calls them `suggested_responses`
https://dev.kik.com/#/docs/messaging#suggested-response-keyboard

Telegram calls them `inline_keyboard` https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating

### PR DESCRIPTION
**Pull request by watadarkstar**
Closes #826 

This is a work in progress. The documentation for this feature can be found here: #881 by @pdoggi 

This will be a collaboration between myself and @pdoggi and the maintainers of this repo.

TODO:

- [x] Initial Docs
- [x] Initial Concept / Work
- [ ] Click event @watadarkstar
- [ ] QuickReplies in Composer.js @pdoggi 
- [ ] System message edge case @pdoggi 
- [ ] Styles 
- [ ] Final code
- [ ] Finalize Docs
- [ ] Fix any lint issues
- [ ] Write Tests
- [ ] Fix any test issues

### CODE REVIEW

**Comment by watadarkstar** [comment]
@xcarpentier @pdoggi We need to decide on whether we want these quick replies to be in `Bubble.js` like I have them or we want to put them in the `Composer.js`, etc. Maybe @xcarpentier you can provide some advice here. 

Keep in mind that we may want to hide these quick replies if its not the latest message so they don't clutter the chat. We also need to consider if a system message is the last message and whether it should hide the quick replies. We need to keep track of the last message (that is not a system message). Or we just keep track of the last message so we can hide the quick replies if the last message does not have quick replies and forget about the system message issues. Or fix that in another PR.

**Comment by pdoggi** [comment]
@watadarkstar I got your branch up and running on my machine. I think you're right that we can do both in `Bubble.js` and `Composer.js`. For my use case, I'm hoping to achieve something that looks like this:

Wysa Screenshot.jpg?raw=true)

My initial thoughts would be to put this over the `TextInput` in `Composer.js`., but could be totally wrong. Open to thoughts!

I agree that we would need to hide quick replies for message bubbles that are not the last one. Probably a good idea to track the last message that's not a system message.

I'm happy to start working on this, but would love to chat about how we'll implement this! @watadarkstar @xcarpentier I've created a [gitter chatroom](https://gitter.im/react-native-gifted-chat/Lobby#) to facilitate. 

Thanks a bunch! Looking forward to working together!

**Comment by pdoggi** [comment]
I just thought about another thing. I think that each quick reply JSON should contain a payload that can be passed to the backend. At least in my use case, I would like to have that ability.

**Comment by watadarkstar** [comment]
Yes for that use case you would put it in the composer. Maybe try doing that and I can help you along the way. @pdoggi

**Comment by watadarkstar** [comment]
@pdoggi :

RE: My initial thoughts would be to put this over the TextInput in Composer.js., but could be totally wrong. Open to thoughts!

I like that approach. Let's work on the `Composer.js` option first, I think it makes the most sense and then we can build out the `Bubble.js` option and have a prop that toggles which one to use. But in this PR lets focus on the `Composer.js` version.

RE: I just thought about another thing. I think that each quick reply JSON should contain a payload that can be passed to the backend. At least in my use case, I would like to have that ability.

Once I implement the click event we won't need this payload and it will make sense on how you can do this. I'll try to work on this next.

RE: I agree that we would need to hide quick replies for message bubbles that are not the last one. Probably a good idea to track the last message that's not a system message.

Do you want to try tackling this @pdoggi ?

**Comment by watadarkstar** [comment]
@xcarpentier @FaridSafi I keep getting this error when I run `npm run sync` inside the `./example` folder. Any ideas what I'm doing wrong?

```
$ npm run sync                                                                                                                                                                                                           

> GiftedChat@0.0.1 sync /Users/adriancaroll/workspace/github/react-native-gifted-chat/example
> rm -rf ./node_modules/react-native-gifted-chat; sane '/usr/bin/rsync -v -a --exclude .git --exclude example --exclude __tests__ --exclude node_modules ../ ./node_modules/react-native-gifted-chat/' .. --glob='{**/*.json,**/*.js}'

2018-06-16 20:07 node[65784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-16 20:07 node[65784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-16 20:07 node[65784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-16 20:07 node[65784] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
``` 

I just need a way to watch files for changes so I can develop this feature faster.

**Comment by watadarkstar** [comment]
@pdoggi do you have write access to my branch I think I gave it to you?

**Comment by xcarpentier** [comment]
Sorry I’m not sure what it is.
But it will cool if you provide a snack link with your branch, since expo sdk 28 it should be possible...

**Comment by pdoggi** [comment]
@watadarkstar Yes, I saw that you gave me write access to your branch. I will tackle moving the code from `Bubble.js` to `Composer.js`. 

I have a newbie question on `npm run sync`, do I make code changes to `./src` and then run `npm run sync` to apply the changes to `./example/node_modules/react-native-gifted-chat/src`?

**Comment by watadarkstar** [comment]
@pdoggi `npm run sync` runs a watchman that watches `"react-native-gifted-chat": "file:..",` for changes. 

`file:...` is expecting that you have the following directory structure:
```
/react-native-gifted-chat/example/`
```

So it watches for changes inside `./react-native-gifted-chat` which is one directory below `./example` and ya so you make changes in `./react-native-gifted-chat/src`

**Comment by pdoggi** [comment]
@watadarkstar Oh I see, that makes sense. Should I be using the [wml library](https://github.com/wix/wml) like the [README.md suggests](https://github.com/watadarkstar/react-native-gifted-chat#notes-for-local-development)?

**Comment by watadarkstar** [comment]
@pdoggi I think that would be a good idea. The example .md seems to say otherwise but I imagine the README is more updated.

**Comment by pdoggi** [comment]
@watadarkstar Ah, now I see the `npm run sync` in the `example/README.md`. I tried the `wml` library and the documented steps are helpful, but missing some information. I burned a few hours trying to get `wml start` to work. I keep getting this error:

```
Bundling `index.ios.js`  70.1% (67/80), failed.
error: bundling failed: "Unable to resolve module `AccessibilityInfo` from `./example/node_modules/react-native/Libraries/react-native/react-native-implementation.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```
So instead, I tried `npm run sync` and got the same error you did:

```
2018-06-18 18:48 node[10698] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-18 18:48 node[10698] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-06-18 18:48 node[10698] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
```

I'll probably for now just `rm -rf example/node_modules/` and then run `yarn install` to sync the files manually. I found a couple issues ([#10028](https://github.com/facebook/react-native/issues/10028) and [#9309](https://github.com/facebook/react-native/issues/9309)) that might explain the FSEvents error, but haven't been able to fix it myself.

**Comment by watadarkstar** [comment]
@pdoggi  ya i saw those issues and i tried re-installing watchman using brew but no luck. I think this might fix it though i just didnt have enough time to kill.

**Comment by xcarpentier** [comment]
I think I will continue soon on this PR, because I will need something like this and it's a good idea to integrate it here.

**Pull request closed without merging**
