### PR TITLE
Feat: Allow QuickReplies component container styles to be customised

### LINKED ISSUE #2270: Allow QuickReplies component container styles to be customised
#### Issue Description

Currently QuickReplies component container styles are hard-coded here: https://github.com/FaridSafi/react-native-gifted-chat/blob/04845b02e88365b18385adab7450fb4a1a515a18/src/QuickReplies.tsx#L135
So, it is impossible to customize it.

Some use cases are:
- Rendering quick replies on the right side rather than left side by default.
- Making the quick replies wider if needed (e.g. on web).
- Making quick replies render vertically always rather than rendering in one row by default & wrapping.

#### Expected Results

QuickReplies component container should be customizable.

#### Additional Information

* Nodejs version: 16.15.0
* React version: 17.0.2
* React Native version: 0.64.3
* react-native-gifted-chat version: 1.0.4
* Platform(s) (iOS, Android, or both?): both
* TypeScript version: 4.7.2

### PR DESCRIPTION
**Pull request by rajatkantinandi**
- closes #2270

### CODE REVIEW

**Review by admehta01 — APPROVED** [review]

**Review by arunpugahz — APPROVED** [review]

**Comment by arunpugahz** [comment]
@FaridSafi ^^

**Comment by arosca** [comment]
Can this be merged please?

**Comment by AshleyBoyd11** [comment]
Would be great if this was merged!

**Comment by rajatkantinandi** [comment]
It feels like this project is abandoned. The last commit was 6 months ago. So, it is outdated and maintainers are probably busy with something else. @xcarpentier or anyone else can merge this and release a version?

**Review by xcarpentier — APPROVED** [review]

**Pull request merged**
