### PR TITLE
(fix) #2287 fixed multiline textinput does not grow anymore

### PR DESCRIPTION
**Pull request by flodev**
Hi,
this is a bugfix for multiline textinputs not growing anymore described in here https://github.com/FaridSafi/react-native-gifted-chat/issues/2287

Don't hesitate to contact if you need more information.

I would be pleased if someone could merge it.

best regards flo

### CODE REVIEW

**Review by Arch1tect — APPROVED** [review]

**Comment by flodev** [comment]
hm after thoroughly testing I've found an issue that'll cause infinite flickering on iOS. I need to dig into this again.

**Comment by flodev** [comment]
Hi there, so I changed the callbacks and replaced the onLayout with onContentSizeChange.
Now growing of the textinput works same as in version 0.16.3
Now I know someone changed it for a reason and I'm keen to know if the onLayout should still be there and what it initially was for?

**Comment by tbergeron** [comment]
When can we expect a new release including this change?

**Comment by gontovnik** [comment]
@Johan-dutoit hey! Could we please create 1.1.1 with the following fix? :)

**Comment by Johan-dutoit** [comment]
I'll get this tested ASAP

**Review by Johan-dutoit — APPROVED** [review]

**Comment by Johan-dutoit** [comment]
FYI this was released in v1.1.1

**Pull request merged**
