### PR TITLE
Ensure react-native-web compatibility

### PR DESCRIPTION
**Pull request by PeterKottas**
This PR makes this lib 100% compatible with react-native-web. Please note this is not yet final, I am opening the PR to give you a chance to look at it and make suggestions. As you can see from package.json, 2 libs had to be replaced with forks so I first need to orchestrate updated release of those before we can have stable version out.
Atm, I am also working on invertible-scroll-view which doesn't work on web. Will let you know once everything is done. In the meantime, folks can use "react-native-gifted-chat": "git+https://github.com/PeterKottas/react-native-gifted-chat#ab3f65dd5883a7cad3691c6accf570a56f245b8d", for testing on web. (it's pretty neat already! ;))

### CODE REVIEW

**Comment by xcarpentier** [comment]
@PeterKottas Thank you!

Looks great :)

Can you provide a real example in the web (ie. on free heroku)?

Did you PR others libs deps to be compatible with RNW? (react-native-action-sheet & react-native-parsed-text)

**Comment by PeterKottas** [comment]
Hey mate, yep, these are the links to keep track of it : 
https://github.com/expo/react-native-action-sheet/pull/77
https://github.com/taskrabbit/react-native-parsed-text/pull/45
I am also investigating the message container compatibility as mentioned here https://github.com/FaridSafi/react-native-gifted-chat/pull/705 in my comments.
Problem is react-native-web doesn't support FlatList yet. So I might need to hack something together either with array of views (mighty stupid) or maybe with section list which might land in react-native-web sooner. 
It's definitely a bit of an uphill battle.
Nope, sorry, no example yet, I might put one somewhere on github pages but first I want to make sure it actually works. 
Our repo where we use this is unfortunately private so I'll probably create one off create-react-web or something.

**Comment by xcarpentier** [comment]
Hi @PeterKottas,
Can you fix lint and tests issues, see all checks on [circleci](https://circleci.com/gh/FaridSafi/react-native-gifted-chat/179?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)?

**Comment by olebedev** [comment]
@xcarpentier, several changes here are dangerous. @PeterKottas, imports packages which are vendored to his own github account. 

I would prodiding a webpack config diff instead.

**Comment by PeterKottas** [comment]
@xcarpentier I should be able to look at those over the weekend.
@olebedev Check my previous comments, this is definitely not ready expecially for the reason you mentioned. There are however links to PRs that once merged into dependencies, we can safely use those.

**Comment by gugakatsi** [comment]
@PeterKottas kinda confused, can i somehow use it on rn-web now?

**Comment by xcarpentier** [comment]
Not yet.
Maybe it will be interesting to look at react-native-dom toi?

**Comment by PeterKottas** [comment]
@xcarpentier and @gugakatsi hi guys, sorry I haven't been paying much attention to this for a while. The thing is more and more I tried to use it, I was discovering some weird hard to fix issues. So what I did instead is I've created a new lib which was meant to support web from the beggning. It's not exactly 100% compatible with this lib but hey, it's chat, it's not rocket science. If you want, you can check it out here. https://github.com/PeterKottas/react-native-bell-chat there's also pure web version here https://github.com/PeterKottas/react-bell-chat

**Pull request closed without merging**
