### PR TITLE
WEB Gifted Chat 

### PR DESCRIPTION
**Pull request by xcarpentier**
Using react-native-web for Gifted Chat.
Next version: [next](https://www.npmjs.com/package/react-native-gifted-chat/v/next)
@EvanBacon

### CODE REVIEW

**Comment by xcarpentier** [comment]
There are issues with <ParseText/> to fix it I'm using @EvanBacon PR and for <Video/> I used platform web and require (not yet tested).

**Comment by EvanBacon** [comment]
It would be great to remove the video as it's a native dependancy. If you create an Expo app (which would have universal support) then you are installing `react-native-video` and not using.

**Comment by xcarpentier** [comment]
@EvanBacon `expo-av` could make the job, no? 
Will you webify it soon?

**Comment by xcarpentier** [comment]
I removed video dependency.

**Comment by zacharyrose** [comment]
Very excited for this feature to merge!

**Comment by n-sviridenko** [comment]
Any updates on this PR?

**Comment by EvanBacon** [comment]
Re: Video support.

We are investigating adding a `.expo` file which would then enable you to use `react-native-video` or `expo-av`. This would preserve the tree-shaking functionality provided by the Expo module and fallback when using other modules.

**Comment by xcarpentier** [comment]
Hi @n-sviridenko,
Thank you for asking.

I have my own project using this web implementation ([here](https://github.com/xcarpentier/vitrine) with [next version](https://www.npmjs.com/package/react-native-gifted-chat/v/next)) 
And another project using the actual version and I will switch to `next` and check if nothing is broken.

[I changed/fixed a lot of code for web](https://github.com/FaridSafi/react-native-gifted-chat/pull/1284/files), because `inverted={false}` prop is better UX and wasn't fully supported.

**If you have a project using GiftedChat, please try this version! And let me know if something is broken:** 
```json
"react-native-gifted-chat": "next",
```
or
```json
"react-native-gifted-chat": "0.10.0-beta.web.18",
```
_(depending on a new version will be out again)_
Thanks :)

**Comment by xcarpentier** [comment]
Hi @EvanBacon,
About `<video/>`, I removed it as you suggested.
I will keep it removed and create another PR later with `.expo.{js,ts,jsx,tsx}` when it will be supported for the web.
Thanks :)

**Comment by ReallyLiri** [comment]
> Hi @n-sviridenko,
> Thank you for asking.
> 
> I have my own project using this web implementation ([here](https://github.com/xcarpentier/vitrine) with [next version](https://www.npmjs.com/package/react-native-gifted-chat/v/next))
> And another project using the actual version and I will switch to `next` and check if nothing is broken.
> 
> [I changed/fixed a lot of code for web](https://github.com/FaridSafi/react-native-gifted-chat/pull/1284/files), because `inverted={false}` prop is better UX and wasn't fully supported.
> 
> **If you have a project using GiftedChat, please try this version! And let me know if something is broken:**
> 
> ```json
> "react-native-gifted-chat": "next",
> ```
> 
> or
> 
> ```json
> "react-native-gifted-chat": "0.10.0-beta.web.18",
> ```
> 
> _(depending on a new version will be out again)_
> Thanks :)

I tried using these versions with RNW, but am still getting build error

`node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (350:16)`

**Comment by xcarpentier** [comment]
> I tried using these versions with RNW, but am still getting a build error
> 
> `node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (350:16)`

@ReallyLiri 
It seems to be a miss or a bad configuration of your environment. 

At this line, this is the first time that we open a react `<component/>`.


Screenshot 2019-07-24 at 13 56 42

Are you sure that you are using babel and have react-native-web transformer set or have [configured everything correctly](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md) ?

**Comment by liiri** [comment]
> > I tried using these versions with RNW, but am still getting a build error
> > `node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (350:16)`
> 
> @ReallyLiri
> It seems to be a miss or a bad configuration of your environment.
> 
> At this line, this is the first time that we open a react `<component/>`.
> 
> Screenshot 2019-07-24 at 13 56 42
> 
> Are you sure that you are using babel and have react-native-web transformer set or have [configured everything correctly](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md) ?

Indeed I seem to be having some bad configuration issues, but let's give it another shot. I altered some stuff in my babel config and managed to build. Now getting error in browser:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at decodeGroupRule (createOrderedCSSStyleSheet.js:144)
    at createOrderedCSSStyleSheet.js:39
    at Array.forEach (<anonymous>)
    at createOrderedCSSStyleSheet (createOrderedCSSStyleSheet.js:35)
    at init (createStyleResolver.js:78)
    at createStyleResolver (createStyleResolver.js:91)
    at Module.../../node_modules/react-native-gifted-chat/node_modules/react-native-web/dist/exports/StyleSheet/styleResolver.js (styleResolver.js:10)
```

`decodeGroupRule
node_modules/react-native-gifted-chat/node_modules/react-native-web/dist/exports/StyleSheet/createOrderedCSSStyleSheet.js:144`

**Comment by ReallyLiri** [comment]
> > I tried using these versions with RNW, but am still getting a build error
> > `node_modules/react-native-gifted-chat/lib/GiftedChat.js: Unexpected token (350:16)`
> 
> @ReallyLiri
> It seems to be a miss or a bad configuration of your environment.
> 
> At this line, this is the first time that we open a react `<component/>`.
> 
> Screenshot 2019-07-24 at 13 56 42
> 
> Are you sure that you are using babel and have react-native-web transformer set or have [configured everything correctly](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md) ?

Indeed I seem to be having some bad configuration issues, but let's give it another shot. I altered some stuff in my babel config and managed to build. Now getting error in browser:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at decodeGroupRule (createOrderedCSSStyleSheet.js:144)
    at createOrderedCSSStyleSheet.js:39
    at Array.forEach (<anonymous>)
    at createOrderedCSSStyleSheet (createOrderedCSSStyleSheet.js:35)
    at init (createStyleResolver.js:78)
    at createStyleResolver (createStyleResolver.js:91)
    at Module.../../node_modules/react-native-gifted-chat/node_modules/react-native-web/dist/exports/StyleSheet/styleResolver.js (styleResolver.js:10)
```
`decodeGroupRule node_modules/react-native-gifted-chat/node_modules/react-native-web/dist/exports/StyleSheet/createOrderedCSSStyleSheet.js:144`

**Comment by xcarpentier** [comment]
@ReallyLiri sorry I deleted your latest message because it appears twice I thought you posted it twice :/
Can you repost it?

BTW this error seems familiar to me but it's still your environment and not this PR. So please fix your environment before (maybe look at [my project](https://github.com/xcarpentier/vitrine/tree/master/apps/mobile)?)

**Comment by batuhansahan** [comment]
SyntaxError: ..\node_modules\react-native-gifte
d-chat\lib\GiftedChat.js: Unexpected token (348:16)


  346 |     renderMessages() {
  347 |         const AnimatedView = this.props.isAnimated === true ? Animated.V
iew : View;
> 348 |         return (<AnimatedView style={{
      |                 ^
  349 |             height: this.state.messagesContainerHeight,
  350 |         }}>
  351 |         <MessageContainer {...this.props} invertibleScrollViewProps={thi
s.invertibleScrollViewProps} messages={this.getMessages()} forwardRef={this._mes
sageContainerRef}/>

**Comment by xcarpentier** [comment]
> SyntaxError: ..\node_modules\react-native-gifte
> d-chat\lib\GiftedChat.js: Unexpected token (348:16)
> 
> ```
> renderMessages() {
>  const AnimatedView = this.props.isAnimated === true ? Animated.View : View;
>  return (<AnimatedView style={{  // error here
>  height: this.state.messagesContainerHeight,
>  }}>
>  <MessageContainer {...this.props} invertibleScrollViewProps={thi
> s.invertibleScrollViewProps} messages={this.getMessages()} forwardRef={this._mes
> sageContainerRef}/>
> ```

Are you sure that you follow [react-native-web steps](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md)?

**Comment by uyogesh** [comment]
Still waiting eagerly for merging of this pull request.

**Comment by zacharyrose** [comment]
> Still waiting eagerly for merging of this pull request.

As am I!

**Comment by adelowo** [comment]
Patiently waiting :)

**Comment by uyogesh** [comment]
> Patiently waiting :)

why are u so patient? i have a project hanging due to this!! and im impatient as f!!

**Comment by xcarpentier** [comment]
Use the « next » tag on npm and let us know your feedback, thanks

**Comment by zacharyrose** [comment]
What's the holdup? Let's merge this in already!

**Comment by xcarpentier** [comment]
Hi @batuhansahan @ReallyLiri,

I tried it myself with `create-react-app` and it's not as easy as I want to.

But I found a solution 🎉
Overriding webpack configuration with `react-app-rewired`

- `yarn add -D react-app-rewired`
- `touch config-overrides.js`
```js
module.exports = function override(config, env) {
  config.resolve = {
    ...config.resolve,
    alias: {
      'react-native$': require.resolve('react-native-web'),
    },
  }
  config.module.rules.push({
    test: /\.js$/,
    exclude: /node_modules[/\\](?!react-native-gifted-chat|react-native-lightbox|react-native-parsed-text)/,
    use: {
      loader: 'babel-loader',
      options: {
        babelrc: false,
        configFile: false,
        presets: [
          ['@babel/preset-env', { useBuiltIns: 'usage' }],
          '@babel/preset-react',
        ],
        plugins: ['@babel/plugin-proposal-class-properties'],
      },
    },
  })

  return config
}
```

**You can find a complete exemple here: https://github.com/xcarpentier/gifted-chat-web-demo**

**Comment by adelowo** [comment]
Trying this out tomorrow.. Thanks for the hardwork @xcarpentier !!!

**Comment by xcarpentier** [comment]
See demo: https://reverent-bardeen-47c862.netlify.com/

**Comment by kaxterzz** [comment]
@xcarpentier first of all thank you for the awesome work..

I'm trying to gifted chat for web and I have followed the sample project that you have created. The thing is I noticed that you have set the dimensions of the current window to the view so `GiftedChat` take the whole window size. 

I tried to using it inside a grid (using material-ui component framework for react) without setting the width and height and `GiftedChat` isn't visible on the window but if I set width and height manually it's visible. 

This is what I have tried in Content component

    `function Content() {
      return (
          <Container>
            <Grid item xs={12} sm={6}>
              <SocketContext.Consumer>
                {socket => <MainChatArea socket={socket} />}
              </SocketContext.Consumer>
            </Grid>
            <Grid item xs={12} sm={6}>
            </Grid>
          </Container>
      );
    }` 

And MainChatArea Component

    `<View>
        <GiftedChat
          messages={this.state.messages}
          onSend={messages => this.onSend(messages)}
          scrollToBottom={true}
          renderUsernameOnMessage={true}
          user={{
            _id: 1,
            name: "You"
          }}
        />
      </View>`

As I said if i set the width and height manually `GiftedChat` is gets visible. Is there a way to inherit the parent width and height ? Like I want `GiftedChat` to take the Grid size.

**Pull request merged**
