### PR TITLE
Removed InteractionManager.runAfterInteractions during init

### PR DESCRIPTION
**Pull request by iclems**
Solves https://github.com/FaridSafi/react-native-gifted-chat/issues/377

### CODE REVIEW

**Comment by stantoncbradley** [comment]
also solves #228.  would love to see this merged so we can use upstream branch again

**Comment by boennemann** [comment]
We're using this commit cherry-picked onto 0.1.3 and it's working really well.
It solved a bug where GiftedChat didn't show up at all in some cases (uninitialized).
In the cases where it did show up it took a really long time to load, and it turns out that now even these cases are fast.

Also we've seen problems with `runAfterInteractions` on Android before, so this will likely benefit Android as well.

We would love to see this land on master 👍

**Comment by iclems** [comment]
I haven't fully tested that yet but I suspect with the new React Navigation project being fully native for transitions, there shouldn't be such issues anymore.

**Comment by kfiroo** [comment]
@iclems Hey, sorry for the delay, I was away for a month.
Can you please fix the conflicts so I can merge this?
Thanks! :)

**Comment by cooperka** [comment]
Ping @iclems this would be great to have!

**Comment by bporter2387** [comment]
Idk if I'm doing something wrong, but I can't get the Chat to render unless I remove the following from onInitialLayoutViewLayout() 
`if (layout.height <= 0) {
      return;
    }`
The layout always comes out 0. I am using conditional component rendering using a switch statement, so maybe that's why? So if 'activeTab == "chat"' then render the giftedChat. I'd more than happy to create a PR with the change if removing that is okay with all of you.

**Comment by cooperka** [comment]
@bporter2387 if you're still having the problem you mentioned above, would you mind opening an issue or a PR so we can discuss in more detail?

**Pull request merged**
