### PR TITLE
Feature(MessageContainer): Add ability to render scrollToBottom after scrolling a provided height

### PR DESCRIPTION
**Pull request by Faolain**
Heavily inspired by @mafiusu 's work here https://github.com/FaridSafi/react-native-gifted-chat/pull/757 . 

I added the following features:

- Option to show the scrollToBottom component(defaults to false)
- User can provide their own scrollComponent (Default is just a semi transparent circular V), 
- User can provide the height upon which the scrollToBottom Component should show (default is 200)

any further thoughts here @xcarpentier or @mafiusu ?

### CODE REVIEW

**Comment by Faolain** [comment]
@xcarpentier added missing props to FlatList (tested functionality and looks good), also added corresponding README information. Any suggestions before we merge? cc: @mafiusu

**Comment by Faolain** [comment]
Is there any reason this wasn't merged when it was approved? It seems like there now have been some recent additions to the repo which have led to conflicts.

**Comment by xcarpentier** [comment]
there is actually no reason. Sorry about conflictuel. I wanted to have the other contributor feed-back like you ask...

**Comment by xcarpentier** [comment]
If you have time to resolve conflict I will include it the next version `0.7.0`. Maybe this week. Thanks.

**Comment by Faolain** [comment]
Sorry just saw this as I was very busy this past week. It seems like you already took care of it though @xcarpentier ! Thanks so much!

**Pull request merged**
