### PR TITLE
fix build & upgrade dependencies

### LINKED ISSUE #1703: Latest React Native 0.62.0: Type Errror: Super expression must either be null or a function
#### Issue Description

When upgrading to the latest version of RN 0.62.0 importing the package leads to `Type Errror: Super expression must either be null or a function`

#### Steps to Reproduce / Code Snippets
1. Upgrade RN to 0.62.0.
2. `import { GiftedChat } from 'react-native-gifted-chat';`
3. Runtime error:
`Type Errror: Super expression must either be null or a function`

#### Expected Results
Gifted Chat to load normally

#### Additional Information
Seems to spawn from `GiftedChat.js` line 3

* Nodejs version: 12.16.1
* React version: 16.11.0
* React Native version: 0.62.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): only tested on Android
* TypeScript version: 3.8.3

### PR DESCRIPTION
**Pull request by ahce**
This PR solves the build.
In general, lint and proptypes errors was fixed

- [x] Closes #1703 
- [x] Build success
- [x] Tests passed
- [x] Linter passed
- [x] Prettier applied
- [x] Upgrade dependencies
- [x] Working expo example (0 warnings)

### CODE REVIEW

**Comment by marcorm** [comment]
Great! Is a new release planned?

**Comment by ahce** [comment]
> Great! Is a new release planned?

I don't know
I hope @xcarpentier or @FaridSafi can review this

**Comment by younes200** [comment]
@xcarpentier please review and release this fix.

**Comment by shamilovtim** [comment]
@xcarpentier @FaridSafi there any way we can get a maintainer in here?

**Pull request merged**
