### PR TITLE
add onPress event

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by FaridSafi** [comment]
Thank you!

**Comment by FaridSafi** [comment]
I changed a bit the API https://github.com/FaridSafi/react-native-gifted-chat/commit/ba543061e68d2cd7c44784efe16fd7bee5ff5d8f

To use the onPress event you will have to do

```jsx
import {GiftedChat, Bubble} from 'react-native-gifted-chat';

<GiftedChat renderBubble={(props) => {
    return (
      <Bubble
        {...props}
        touchableProps={{
          onLongPress: null,
          onPress: () => {
            alert('onPress');
          },
        }}
      />
    );
}}
```

but I recommend to use `onLongPress` instead of `onPress`

**Comment by kesha-antonov** [comment]
Thanks!

I need to use onPress and onLongPress together for different actions

**Comment by manjeet-dobble** [comment]
@FaridSafi I tried as suggested by you , but onPress don't seems working, I also checked source for Bubble.js and there is no onPress function as shown in this [link](https://github.com/FaridSafi/react-native-gifted-chat/commit/ba543061e68d2cd7c44784efe16fd7bee5ff5d8f)

**Comment by kfiroo** [comment]
@manjeet-dobble the `onPress` is set [here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/Bubble.js#L105)

**Pull request merged**
