### PR TITLE
Support renderUsername

### PR DESCRIPTION
**Pull request by minhchienwikipedia**
We have the prop `renderUsername` but didn't use it before and we can't custom username's view. So I just return the `renderUsername` to allow custom username's view

### CODE REVIEW

**Comment by minhchienwikipedia** [comment]
@FaridSafi can you check it?

**Comment by Johan-dutoit** [comment]
Seems like a reasonable change.  Please update the documentation too @minhchienwikipedia

**Comment by minhchienwikipedia** [comment]
@Johan-dutoit I just update it

**Comment by baltagih2** [comment]
Hello all, this was never merged and the renderUsername prop still doesn't work

**Comment by minhchienwikipedia** [comment]
@Johan-dutoit can you merge it?

**Pull request merged**
