### PR TITLE
Option to provide custom text inside Day/time components

### PR DESCRIPTION
**Pull request by piotrponikowski**
This PR adds option to pass custom text instead default behavior of Day and Time components. I have some usecases when I need to display custom message instead using default logic, like to display "just now" when createdAt + 5s > now

### CODE REVIEW

**Comment by piotrponikowski** [comment]
Is there any chance to merge?

**Comment by piotrponikowski** [comment]
@xcarpentier what are next steps to proceed with this PR?

**Comment by xcarpentier** [comment]
✅ I don’t see any snapshots updated, are you sure you executed test?

**Comment by piotrponikowski** [comment]
No snapshots have been updated:
```
> set TZ=Europe/Paris && jest --no-watchman

 PASS  src/__tests__/Avatar.test.tsx
 PASS  src/__tests__/Time.test.tsx
 PASS  src/__tests__/GiftedChat.test.tsx
 PASS  src/__tests__/Bubble.test.tsx
 PASS  src/__tests__/Message.test.tsx
 PASS  src/__tests__/Day.test.tsx
 PASS  src/__tests__/MessageContainer.test.tsx
 PASS  src/__tests__/SystemMessage.test.tsx
 PASS  src/__tests__/Composer.test.tsx
 PASS  src/__tests__/Actions.test.tsx
 PASS  src/__tests__/LoadEarlier.test.tsx
 PASS  src/__tests__/InputToolbar.test.tsx
 PASS  src/__tests__/GiftedAvatar.test.tsx
 PASS  src/__tests__/utils.test.ts
 PASS  src/__tests__/Constant.test.tsx
 PASS  src/__tests__/MessageText.test.tsx
 PASS  src/__tests__/Color.test.tsx
 PASS  src/__tests__/Send.test.tsx
 PASS  src/__tests__/MessageImage.test.tsx

Test Suites: 19 passed, 19 total
Tests:       23 passed, 23 total
Snapshots:   21 passed, 21 total
Time:        6.875s, estimated 9s
Ran all test suites.
```

Should I add test which use new props?

**Comment by piotrponikowski** [comment]
@xcarpentier can you please help me with this PR?

**Comment by piotrponikowski** [comment]
@xcarpentier please help

**Pull request closed without merging**
