### PR TITLE
Add flow typedefs

### LINKED ISSUE #1395: Flow typedefs
is there any plan to add flow definitions?

### PR DESCRIPTION
**Pull request by amiralies**
Closes #1395

### CODE REVIEW

**Comment by xcarpentier** [comment]
Hi,
Sorry, but can you resolve conflicts?
I will merge it after your resolving.

**Comment by amiralies** [comment]
there is no conflict with master branch

**Comment by xcarpentier** [comment]
Hi @amiralies,
Thanks for this PR!
I try to find a way to automate it because I didn't use flow and I won't update it myself, I think.
To keep it up to date, what do you think if we use this solution: https://github.com/joarwilk/flowgen?
Do you have some time to investigate it?

**Comment by amiralies** [comment]
@xcarpentier flowgen doesn't convert all types properly, sepcially external libs such as React native and React

**Comment by amiralies** [comment]
@xcarpentier can you release alpha / rc version as next realse on npm so i can test and expermient with flow types?

**Comment by xcarpentier** [comment]
You can test on this version: `0.10.2-0`

**Pull request merged**
