### PR TITLE
fix-extra spacing shown when avatar is not rendered

### PR DESCRIPTION
**Pull request by varungupta85**
Related to issue #445 

I have added a new prop `shouldRenderAvatar` to control whether a user wants to render an avatar or not. I will document this property if the maintainers agree with the solution.

### CODE REVIEW

**Comment by varungupta85** [comment]
I am okay with that. I will make the change.

**Comment by varungupta85** [comment]
@cooperka I have made the change you requested and also updated the README.

**Comment by cooperka** [comment]
I haven't tested on a device, but code LGTM. I also don't have the ability to merge, you'll have to wait for a collaborator for that.

**Comment by varungupta85** [comment]
@cooperka Thanks for reviewing. I have tested it on both Android and iOS devices on my side. I will wait for a collaborator to merge the changes.

cc @kfiroo @FaridSafi

**Comment by thebigredgeek** [comment]
When will this be released?

**Comment by henrythach** [comment]
This breaks the default behavior of showing avatars if developers don't specify a function for `renderAvatar`.  This is because `renderAvatar` is set to `null`, by default, in GiftedChat.js ([See here](https://github.com/FaridSafi/react-native-gifted-chat/blob/master/src/GiftedChat.js#L496)).

**Comment by cooperka** [comment]
@henrythach I have the same problem; simple fix is defaulting `renderAvatar` to `undefined` instead of `null`. It's strange that these are all manually defaulted to `null`, I'm not sure what benefit that would give. I'll open a PR to fix this bug.

**Comment by yurykorzun** [comment]
When will this fix be published to the npm registry?

**Pull request merged**
