### PR TITLE
Break add new ActionSheet

### LINKED ISSUE #1703: Latest React Native 0.62.0: Type Errror: Super expression must either be null or a function
#### Issue Description

When upgrading to the latest version of RN 0.62.0 importing the package leads to `Type Errror: Super expression must either be null or a function`

#### Steps to Reproduce / Code Snippets
1. Upgrade RN to 0.62.0.
2. `import { GiftedChat } from 'react-native-gifted-chat';`
3. Runtime error:
`Type Errror: Super expression must either be null or a function`

#### Expected Results
Gifted Chat to load normally

#### Additional Information
Seems to spawn from `GiftedChat.js` line 3

* Nodejs version: 12.16.1
* React version: 16.11.0
* React Native version: 0.62.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): only tested on Android
* TypeScript version: 3.8.3

### PR DESCRIPTION
**Pull request by ahce**
- This PR closes #1703 
- Break the previous behavior of the ActionSheet for Android, for more information read 
[expo-action-sheet](https://github.com/expo/react-native-action-sheet/blob/master/README.md)
- Same behavior with options for Android & iOS & Web
- Doesn't depend of external packages
- Required to upgrade to react-native 0.62!

## Android
image

## iOS
image

## Web
image

### CODE REVIEW

**Comment by marcorm** [comment]
Hi @ahce , I tried your fork. It doesn't start in our project, I think it's because of:
`"main": "node_modules/expo/AppEntry.js",`
in tour `package.json`

Is it possible?

**Comment by ahce** [comment]
> Hi @ahce , I tried your fork. It doesn't start in our project, I think it's because of:
> `"main": "node_modules/expo/AppEntry.js",`
> in tour `package.json`
> 
> Is it possible?

Hi @marcorm to test this fork in your project, follow these steps:

1. Clone the fork
2. Run yarn install
3. Run yarn build (this creates a lib folder)
4. In your project replace "./node_modules/react-native-gifted-chat/lib" with the build from the previous step
5. In your project install react-native-typing-animation

**Comment by shamilovtim** [comment]
> Required to upgrade to react-native 0.62!

This isn't ready for Expo yet then? Might wanna hold off on this PR

**Comment by enosh94** [comment]
Not building


$ yarn build                                                                                                                                                                                     yarn run v1.22.0                                                                                                                                                                                 $ rm -rf lib/ && node_modules/.bin/tsc && cp flow-typedefs/*.js.flow lib/                                                                                                                        src/Avatar.tsx:88:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                          Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                88       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                       node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Avatar.tsx:89:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                          Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                89       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Avatar.tsx:92:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                          Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                92       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                       node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Avatar.tsx:93:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                          Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                93       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Bubble.tsx:216:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                216       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Bubble.tsx:217:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                217       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                     node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Bubble.tsx:220:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                220       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Bubble.tsx:221:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                221       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                     node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Bubble.tsx:224:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                224       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Bubble.tsx:225:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                225       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                     node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Bubble.tsx:230:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                230       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Bubble.tsx:231:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                231       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                     node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Bubble.tsx:234:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                234       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Bubble.tsx:235:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                235       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                     node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Message.tsx:86:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                86       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                       node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Message.tsx:87:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                         Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                87       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/MessageText.tsx:95:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                     Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                95       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                       node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/MessageText.tsx:96:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                     Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                96       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/Time.tsx:80:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                            Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                80       left: {},                                                                                                                                                                                        ~~~~                                                                                                                                                                                                                                                                                                                                                                                       node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'left' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                              src/Time.tsx:81:7 - error TS2322: Type '{}' is not assignable to type 'Validator'.                                                                                                            Type '{}' provides no match for the signature '(props: { [key: string]: any; }, propName: string, componentName: string, location: string, propFullName: string): Error \| null'.                                                                                                                                                                                                                81       right: {},                                                                                                                                                                                       ~~~~~                                                                                                                                                                                                                                                                                                                                                                                      node_modules/@types/prop-types/index.d.ts:51:32                                                                                                                                                    51 export type ValidationMap = { [K in keyof T]?: Validator };                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                           The expected type comes from property 'right' which is declared here on type 'ValidationMap'                                                                                                                                                                                                                                                                                             src/TypingIndicator.tsx:3:33 - error TS7016: Could not find a declaration file for module 'react-native-typing-animation'. 'F:/projects/React-Native/ADDUTIOAL DEPENDENCIES/react-native-gifted- chat_fork/node_modules/react-native-typing-animation/index.js' implicitly has an 'any' type.                                                                                                       Try `npm install @types/react-native-typing-animation` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-typing-animation';`                                                                                                                                                                                                                          3 import { TypingAnimation } from 'react-native-typing-animation'                                                                                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                 src/TypingIndicator.tsx:11:19 - error TS6133: 'setYCoords' is declared but its value is never read.                                                                                                                                                                                                                                                                                               11   const [yCoords, setYCoords] = useState(new Animated.Value(200))                                                                                                                                                  ~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                   src/TypingIndicator.tsx:12:23 - error TS6133: 'setHeightScale' is declared but its value is never read.                                                                                                                                                                                                                                                                                           12   const [heightScale, setHeightScale] = useState(new Animated.Value(0))                                                                                                                                                ~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                           src/TypingIndicator.tsx:13:23 - error TS6133: 'setmarginScale' is declared but its value is never read.                                                                                                                                                                                                                                                                                           13   const [marginScale, setmarginScale] = useState(new Animated.Value(0))                                                                                                                                                ~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Found 24 errors.                                                                                                                                                                                                                                                                                                                                                                                  error Command failed with exit code 2.                                                                                                                                                           info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
--

**Comment by ahce** [comment]
close, see #1743

**Pull request closed without merging**
