### PR TITLE
Implemented ScrollToBottom component while scrolling through the messages.

### PR DESCRIPTION
**Pull request by mafiusu**
Implemented a ScrollToBottom Component. Activated while scrolling through the messages.

Questions to ask:
- better to implement some icon library
- let the user to render the component by himself using props.

https://github.com/FaridSafi/react-native-gifted-chat/issues/698

### CODE REVIEW

**Comment by mafiusu** [comment]
Let me now, if there is a request/desire for this feature. If yes, I will improve that pull request to allow rendering by the user. @xcarpentier @brunocascio

**Comment by amalamarypaul** [comment]
Any update on the PR?

**Comment by xcarpentier** [comment]
Author should resolve conflict first

**Comment by mafiusu** [comment]
> Any update on the PR?

I will resolve the conflicts if I have more time and I'll update this PR :)

**Pull request closed without merging**
