### PR TITLE
Fixing issue with flatlist as its not re-rendering on update

### PR DESCRIPTION
**Pull request by nandiniparimi1107**
Flatlist isnt updating on renderFooter update. Hence adding extraData prop to flatList so that the ui gets updated correctly.

### CODE REVIEW

**Comment by xcarpentier** [comment]
Can you please pull the latest master, thx ;)

**Comment by nandiniparimi1107** [comment]
@xcarpentier I pulled the latest master before putting a pull request out ;)

Actually,  i am using this library version (0.5.0) in my project. That version has the issue with the renderFooter. Is there a version that has this issue fixed?

**Comment by xcarpentier** [comment]
Yes I Know you did but there is an issue with your build due to instable state of master where you pull it first time. So please re-pull it and after I will merge ;)

**Comment by nandiniparimi1107** [comment]
@xcarpentier Thanks i merged it now. Could you please let me know if this change will be released soon? and the version number.

**Comment by nandiniparimi1107** [comment]
@sibelius do you have any suggestions to fix this?

**Comment by sibelius** [comment]
We can have a prop extraData and decide the user decide when to rerender the flatlist

**Comment by xcarpentier** [comment]
@nandiniparimi1107 can you create a Newton PR with this new prop?

**Pull request merged**
