### PR TITLE
replace onChange to onContentSizeChange

### PR DESCRIPTION
**Pull request by devjaw**

### CODE REVIEW

**Comment by cooperka** [comment]
Thanks for the PR! There's a similar PR here as well: https://github.com/FaridSafi/react-native-gifted-chat/pull/502. Curious what your thoughts are on which fix is better.

Can you please explain why this change is needed and what it does?

**Comment by devjaw** [comment]
hello, 
because  contentSize property was removed from TextInput.onChange event in RN0.46.1.
source : [bac84ce207a0466cec95626131063751eb48b964](https://github.com/facebook/react-native/commit/bac84ce207a0466cec95626131063751eb48b964)

**Comment by cooperka** [comment]
Thanks for the link, description there makes sense 👍

**Comment by jayarprado** [comment]
@cooperka Any idea when this can be included in the release? Thanks!

**Comment by cooperka** [comment]
@jayarprado see discussion in [#502](https://github.com/FaridSafi/react-native-gifted-chat/pull/502#issuecomment-314190419).

I'll test this change within the next few days and then release! Just want to make sure it's not breaking for older versions. For now feel free to refer to the direct commit hash in your app if you need this, e.g. `"react-native-gifted-chat": "FaridSafi/react-native-gifted-chat#632c4564b3422c2ddd7e20b2b10e02bae80d0a49"`.

**Comment by cooperka** [comment]
Hi @bilalsyed001, would you mind opening an issue so we can discuss? It would be helpful if you provide more information in the issue, e.g. a screenshot and steps to reproduce it.

**Comment by juhose** [comment]
photo6035171591052175769


Text input field doesnt rise, when I press it. But there is not error when sending anymore

**Comment by cooperka** [comment]
Hi @juhose, this PR is not a good place to discuss, please open a new issue if you're having problems.

**Comment by cooperka** [comment]
Should be fixed in https://github.com/FaridSafi/react-native-gifted-chat/releases/tag/v0.2.5.

**Pull request merged**
