### PR TITLE
Fix avatar placeholder issue

### PR DESCRIPTION
**Pull request by vinayr**
Fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/308 https://github.com/FaridSafi/react-native-gifted-chat/issues/541

### CODE REVIEW

**Comment by brunocascio** [comment]
Hi, 

Thanks for contributing!

It seems to be not resolved in android:

screenshot_1509159522

**Comment by vinayr** [comment]
@brunocascio I updated the fix. It should work properly now.

**Comment by vadimshvetsov** [comment]
@brunocascio Is it possible to merge this?

**Comment by brunocascio** [comment]
@vinayr Could you test the latest changes on master and tell me if it is works without this PR? :)

@vadimshvetsov Which version are you using? (could you try with master branch?)

**Comment by vadimshvetsov** [comment]
I've tried with a master branch. It's not working without this PR

**Pull request closed without merging**
