### PR TITLE
Bot message implementation (quick replies copy and inspiration)

### LINKED ISSUE #826: RFC: Quick Replies
Not sure if this library can do suggested responses but it would be very helpful for people who build chat bots.

Something like this:
customer-chat

Facebook calls them `quick_replies`: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

Kik calls them `suggested_responses`
https://dev.kik.com/#/docs/messaging#suggested-response-keyboard

Telegram calls them `inline_keyboard` https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating

### PR DESCRIPTION
**Pull request by xcarpentier**
## Description 
Start to provide a solution to add quick replies list component between `MessageContainer` and `Composer`.

Image-1 (1)

## Limitations
- In this first implementation, we just provide a single (radio) and multiple (checkbox) selections of option present to the user.

## Data definition and example
```ts

interface Reply {
  title: string,
  value: string
}

interface QuickReplies {
  type: 'radio' | 'checkbox',
  values: Reply[]
}
```
```js
{
  _id: 123,
  text: 'This is a quick reply. Do you love Gifted Chat?',
  createdAt: new Date(),
  quickReplies: {
    type: 'radio', // or 'checkbox',
    values: [
      {
        title: '😋 Yes',
        value: 'yes',
      },
      {
        title: '📷 Yes, let me show you with a picture!',
        value: 'yes_picture',
      },
      {
        title: '😞 Nope. What?',
        value: 'no',
      },
    ],
  },
}
```
### Pull-requests
- [WIP Quick Replies](https://github.com/FaridSafi/react-native-gifted-chat/pull/886)
- [Initial commit updating README.md to include new Quick Reply feature.](https://github.com/FaridSafi/react-native-gifted-chat/pull/881)
- [Add support for onPress on Bubble](https://github.com/FaridSafi/react-native-gifted-chat/pull/984)
### Issues
- [RFC: Quick Replies](https://github.com/FaridSafi/react-native-gifted-chat/issues/826)
- [Rendering Custom Responses (Like a Bot)](https://github.com/FaridSafi/react-native-gifted-chat/issues/367)

Closes #826

### CODE REVIEW

**Comment by xcarpentier** [comment]
Untitled

**Comment by MLK57** [comment]
This feature interests me a lot, do you have an idea of ​​when it will be functional and available ?

**Comment by xcarpentier** [comment]
> This feature interests me a lot, do you have an idea of ​​when it will be functional and available ?

ASAP
but you already can use it here on npm: 0.9.0-beta.0 (next)

**Comment by MLK57** [comment]
> > This feature interests me a lot, do you have an idea of ​​when it will be functional and available ?
> 
> ASAP
> but you already can use it on npm: 0.9.0-beta.0 (next)

I have implemented your feature in my project, do you have Skype, Slack or some other way for me to ask you some questions?

**Comment by xcarpentier** [comment]
> I have implemented your feature in my project, do you have Skype, Slack or some other way for me to ask you some questions?

Yes you can find me here: https://slack.reactnative.gallery/

**Comment by xcarpentier** [comment]
@MLK57 can you please test the next: 0.9.0-beta.4 ?

**Comment by xcarpentier** [comment]
`0.9.0-beta.6`

**Comment by paolospag** [comment]
@xcarpentier I'm trying this new feature now and I have to say it's a great idea!
But I was wondering if it is possible to add the support of the quick replies also in the system messages, to be used for example as the first message to start the conversation (like Facebook Messenger).

Do you think it is possible?

**Comment by avillega** [comment]
Great functionality so far. How ever it is very difficult to customize the QuickReplies component. Adding a few style props to the component would make it more configurable and customizable

**Comment by xcarpentier** [comment]
@paolospag & @avillega your ideas are excellent!
Feel free to create PR to customize more and another one PR with a `system` kind of quick replies (like facebook messenger)

**Comment by moschap** [comment]
Hi @xcarpentier, really good job you have done here.
Please one question how do i style the quickReply bubbles? I have added this in the GiftedChat component but it doesn't reflect.
`<GiftedChat
                        showUserAvatar={false}
                        showAvatarForEveryMessage={false}
                        messages={this.props.chatMessages}
                        onSend={messages => this.onSend(messages)}
                        onQuickReply={this.onQuickReplyEvent}
                        quickReplyStyle={{ color: "red", borderColor: "red"}}
                        renderSend={this.renderSend}
                        minInputToolbarHeight={65}
                        
                        user={{
                            _id: this.props.userProfile.data.user.personal.phoneNos,
                            name: this.props.userProfile.data.user.personal.phoneNos
                        }}
                    />`

**Comment by nzrin** [comment]
How to customize onQuickReply bubble and how to make it flexdirection:row enabled instead of putting the option side by side.

**Pull request merged**
