### PR TITLE
Add prop to always show send button

### LINKED ISSUE #546: How to make the SendButton always show?
#### Issue Description

[FILL THIS OUT]

#### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

#### Additional Information

* React Native version: [FILL THIS OUT]
* react-native-gifted-chat version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

### PR DESCRIPTION
**Pull request by apparition47**
Resolves #546 

We really need an option to always show the send button. Prop is defaulted to false to maintain existing behaviour.

Usage:
```html
        <GiftedChat
          alwaysShowSend={true}
        />
```

### CODE REVIEW

**Comment by xcarpentier** [comment]
Can we just merge master into you PR?

**Comment by apparition47** [comment]
Who's in charge of merging this?

**Comment by xcarpentier** [comment]
I mean please fix conflict and pull master into your branch...

**Comment by apparition47** [comment]
Done

**Comment by apparition47** [comment]
Done. Don't see a conflict ATM.

**Comment by brunocascio** [comment]
LGTM

**Comment by AntoineGrandchamp** [comment]
@xcarpentier When will this be available on NPM ?

**Pull request merged**
