### PR TITLE
Added isCustomViewBottom Prop

### PR DESCRIPTION
**Pull request by Lsleiman**
Seems like this feature request keeps coming back. Most frequent use case is having Accept/Reject buttons rendered underneath the message text.

Users can now determine if their custom view is rendered before or after bubble message, image or video.

### CODE REVIEW

**Comment by Lsleiman** [comment]
See #1246 and #1201

**Comment by Lsleiman** [comment]
I went ahead and changed the propType to Boolean with a default value of false. Let me know if i missed anything.
CustomView will display at the top unless users specifically set renderCustomViewBottom = true.

**Comment by xcarpentier** [comment]
Sorry but I don't think this is a cristal clear name of props `renderCustomViewBottom`.
When `boolean` props I prefer I prefer something like  `isCustomViewBottom`.

**Comment by Lsleiman** [comment]
mmm, I basically used _renderAvatarOnTop_, but will change and resubmit.

**Comment by robertvorthman** [comment]
Did isCustomViewBottom get compiled into the lib .js files?   I can't get isCustomViewBottom to work and it does not appear appear in the Bubble.js file at node_modules/react-native-gifted-chat/lib/Bubble.js.

**Comment by andersravn** [comment]
Was this ever included? Would be really nice to be able to add custom view such as buttons after the text.

**Pull request merged**
