### PR TITLE
Implement shouldUpdateMessage, supersedes #1187

### PR DESCRIPTION
**Pull request by simonasdev**
Please merge this and close #1187

### CODE REVIEW

**Comment by xcarpentier** [comment]
Hi,
Thanks but you missed the TypeScript definition.

**Comment by simonasdev** [comment]
@xcarpentier good catch, did I add them correctly now?

**Comment by xcarpentier** [comment]
You should also define it to `<GiftedChat/>` component.

**Comment by simonasdev** [comment]
done that, looks good?

**Pull request merged**
