### PR TITLE
fix(keyboard height): fix on android & expo TextInput no show

### PR DESCRIPTION
**Pull request by xcarpentier**
* adding forceGetKeyboardHeight props
* fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/461
* fixes https://github.com/FaridSafi/react-native-gifted-chat/issues/518

### CODE REVIEW

**Comment by cooperka** [comment]
Hi @xcarpentier, issue #461 is a question about how to use this library with Expo, which is already resolved and seems unrelated. Can you please give more details about the issue you're trying to solve with this?

**Comment by xcarpentier** [comment]
Hi @cooperka,

Thank you very much for your reply! 👍

The issue I want to fix is this one https://github.com/FaridSafi/react-native-gifted-chat/issues/518

Actually Expo changed some configurations in latest versions into android, such as `android:windowSoftInputMode="adjustResize"`. This changement cause no show TextInput on focus into android & into Expo app, the TextInput is just not shown.

Please refer to this related issues:
- [Android theme causes Window not to resize when keyboard is open](https://forums.expo.io/t/android-theme-causes-window-not-to-resize-when-keyboard-is-open/1582)
- This comment from @llamaluvr correspond to the SDK-19 or SDK-20 when some configuration change into Expo: [comment](https://github.com/FaridSafi/react-native-gifted-chat/issues/461#issuecomment-314577896)

The calculation of the height of the keyboard took place after v0.1.4 release: 
https://github.com/FaridSafi/react-native-gifted-chat/compare/v0.1.4...v0.1.5#diff-a2356064fe377d125c72f41f52d4dad5R157


The buggy result is:
image

**Comment by xcarpentier** [comment]
@cooperka any other suggestion ?

**Comment by coreyac** [comment]
Haven't perfected it yet, but appears technique 1 listed here may fix the issue with Android: https://medium.freecodecamp.org/how-to-make-your-react-native-app-respond-gracefully-when-the-keyboard-pops-up-7442c1535580

**Comment by xcarpentier** [comment]
Hello @coreyac,
Do you mean KeyboardAvoidingView ?

This is not supported in last android version and react-native version. I have many issue with it...

Actually this PR fixed the problem for old android version like 4.4.x. (api version < 21)

```jsx
<GiftedChat
  forceGetKeyboardHeight={
    Platform.OS === 'android' && Platform.Version < 21
   }
/>
```

**Comment by coreyac** [comment]
@xcarpentier Appreciate the heads up about last android version. Hadn't tested that yet. I'll try out the forceGetKeyboardHeight prop. Thanks!

**Comment by brunocascio** [comment]
Guys, any update here? :)

**Comment by xcarpentier** [comment]
@brunocascio @cooperka if someone not wanted to merged it if not agree.

This is not a breaking change.

BTW I think I will add a small doc in readme about this new props and explain correctly what does it mean.

Let me know, but I have the ability to merge PR too.

**Comment by brunocascio** [comment]
LGTM

**Pull request merged**
