### PR TITLE
Updating font to avenir

### PR DESCRIPTION
**Pull request by jakehasler**

### CODE REVIEW

**Comment by kfiroo** [comment]
@jakehasler I feel like setting the font should be a customisable to the user and not hard coded
What do you think?

**Comment by paramaggarwal** [comment]
Will this even work on Android? This feels wrong to me.

**Comment by FaridSafi** [comment]
Hi, you set a custom font using `renderMessage`

**Comment by jakehasler** [comment]
@kfiroo @FaridSafi I apologize for the accidental PR here. I meant to perform the change to a forked version. Thanks for the `renderMessageText` input - I'll be sure to implement that. Thanks for a great module!

**Pull request closed without merging**
