### PR TITLE
Scroll to bottom on messages prop change + Style fix

### PR DESCRIPTION
**Pull request by slavik0329**
When messages prop is changed, we should scroll to the bottom to get latest messages into view
Name style fix

### CODE REVIEW

**Comment by niftylettuce** [comment]
@slavik0329 Is this related to https://github.com/FaridSafi/react-native-gifted-messenger/issues/35?

**Comment by slavik0329** [comment]
@niftylettuce yes, I think this should solve that problem

**Comment by niftylettuce** [comment]
@slavik0329 Unfortunately it didn't :frowning:, I just installed your fork with this commit and it hasn't resolved it.

**Comment by slavik0329** [comment]
@niftylettuce ah, nevermind. I thought you were having the same issue where the messages did load, but were just hidden from view

**Comment by niftylettuce** [comment]
Figured it out, I had to upgrade to RN 0.18+ because of `onLayout`

**Comment by ckurban** [comment]
I have similar issue, in iso (havent tried in android yet) after loading earlier messages from remote it does not scroll to bottom, is what you see guys ?

**Comment by koppelaar** [comment]
A related issue is that when there are only a few messages in the listview (so the messages do NOT fill up the screen) and the keyboard is shown, it is customary for chat apps to scroll to the bottom. Users are typically replying to the last message and this scroll action ensures that the last message is still visible. This scroll action usually happens at the same time the keyboard is becoming visible.

**Pull request closed without merging**
